// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Stream = require("stream");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var c1 = new Console({
      stderr: new Stream.Writable(),
      ignoreErrors: false,
      colorMode: true,
      inspectOptions: { },
      stdout: new Stream.Writable()
    });

var c2 = new Console({
      stderr: Caml_option.some(new Stream.Writable()),
      ignoreErrors: false,
      colorMode: true,
      inspectOptions: { },
      stdout: new Stream.Writable()
    });

exports.c1 = c1;
exports.c2 = c2;
/* c1 Not a pure module */
