// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Console = require("console");
var Process = require("process");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var c1 = new Console.Console({
      stderr: Caml_option.some(Process.stderr),
      ignoreErrors: false,
      colorMode: true,
      inspectOptions: { },
      stdout: Process.stdout
    });

var c2 = new Console.Console({
      stderr: Caml_option.some(Process.stderr),
      ignoreErrors: false,
      colorMode: true,
      inspectOptions: { },
      stdout: Process.stdout
    });

var c3 = new Console.Console({
      stderr: Process.stderr,
      ignoreErrors: false,
      colorMode: true,
      inspectOptions: { },
      stdout: Process.stdout
    });

c1.log("a", "b");

c2.table([
      "hi",
      "bye"
    ]);

c2.table([Js_dict.fromArray([
            /* tuple */[
              "a",
              1
            ],
            /* tuple */[
              "b",
              2
            ]
          ])]);

exports.c1 = c1;
exports.c2 = c2;
exports.c3 = c3;
/* c1 Not a pure module */
