// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Stream = require("stream");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Console$NodeJs = require("../src/Console.bs.js");

var c1 = Console$NodeJs.make(Caml_option.some(new Stream.Writable()), false, true, { }, new Stream.Writable());

exports.c1 = c1;
/* c1 Not a pure module */
