// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Assert = require("assert");

Assert.equal(Path.posix.basename("/tmp/myfile.html"), "myfile.html");

/*  Not a pure module */
