// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function string(a) {
  return a;
}

function buffer(a) {
  return a;
}

function int8Array(a) {
  return a;
}

function uInt8Array(a) {
  return a;
}

function uInt8ClampedArray(a) {
  return a;
}

function uInt16Array(a) {
  return a;
}

function int16Array(a) {
  return a;
}

function uInt32Array(a) {
  return a;
}

function int32Array(a) {
  return a;
}

function float32Array(a) {
  return a;
}

function float64Array(a) {
  return a;
}

function dataView(a) {
  return a;
}

exports.string = string;
exports.buffer = buffer;
exports.int8Array = int8Array;
exports.uInt8Array = uInt8Array;
exports.uInt8ClampedArray = uInt8ClampedArray;
exports.uInt16Array = uInt16Array;
exports.int16Array = int16Array;
exports.uInt32Array = uInt32Array;
exports.int32Array = int32Array;
exports.float32Array = float32Array;
exports.float64Array = float64Array;
exports.dataView = dataView;
/* No side effect */
