// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Constants = { };

function setPoolSize(n) {
  return Buffer.poolSize = n;
}

exports.Constants = Constants;
exports.setPoolSize = setPoolSize;
/* No side effect */
