// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Events$NodeJs = require("./Events.bs.js");

Events$NodeJs.EventEmitter.Impl({ });

var $$Worker = { };

exports.$$Worker = $$Worker;
/*  Not a pure module */
