// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function Impl(T) {
  return { };
}

var EventEmitter = {
  Impl: Impl
};

exports.EventEmitter = EventEmitter;
/* No side effect */
