// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Constants = { };

var Stat = { };

var Handle = { };

var WriteStream = { };

var ReadStream = { };

exports.Constants = Constants;
exports.Stat = Stat;
exports.Handle = Handle;
exports.WriteStream = WriteStream;
exports.ReadStream = ReadStream;
/* No side effect */
