// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var IncomingMessage = { };

var ServerResponse = { };

var Server = { };

exports.IncomingMessage = IncomingMessage;
exports.ServerResponse = ServerResponse;
exports.Server = Server;
/* No side effect */
