// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

function $slash(prim, prim$1) {
  return Path.join(prim, prim$1);
}

function $slash$1(prim, prim$1) {
  return Path.posix.join(prim, prim$1);
}

var Posix = {
  $slash: $slash$1
};

function $slash$2(prim, prim$1) {
  return Path.win32.join(prim, prim$1);
}

var Win32 = {
  $slash: $slash$2
};

exports.$slash = $slash;
exports.Posix = Posix;
exports.Win32 = Win32;
/* path Not a pure module */
