// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Readable = { };

var Writable = { };

var Duplex = { };

var Transform = { };

var PassThrough = { };

exports.Readable = Readable;
exports.Writable = Writable;
exports.Duplex = Duplex;
exports.Transform = Transform;
exports.PassThrough = PassThrough;
/* No side effect */
