// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Url = require("url");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

var SearchParams = { };

function format(auth, fragment, search, unicode, url) {
  return Url.format(url, {
              auth: Js_null_undefined.fromOption(auth),
              fragment: Js_null_undefined.fromOption(fragment),
              search: Js_null_undefined.fromOption(search),
              unicode: Js_null_undefined.fromOption(unicode)
            });
}

exports.SearchParams = SearchParams;
exports.format = format;
/* url Not a pure module */
